### PR TITLE
enhancement: custom-docker-config

### PR DESCRIPTION
**Pull request by khawkins98**
Follows #24 to setup a SiS sepcific config.

Still in progress:

- [x] Remove unneeded logic
- [ ] Ensure correct things are activated
- [x] Docs

### CODE REVIEW

**Comment by khawkins98** [comment]
I've updated this to remove a good bit of the unneeded things and running `bin/dev quick_blank` will set up a basic VF WP site (with needed vf-wp plugins and themes).

This will probably need more tweaks and there are likely more things that we can remove, but it seems to work well enough for now.

It's also probably not worth forking more than we need to, as that way it will be easier to bring in upstream updates.

**Comment by khawkins98** [comment]
To test this from scratch — this will delete any local project setup using the `bin/dev` method!

1. `bin/dev down`
2. Stop and start docker
3. Remove local SQL `rm -rf _*` (will delete any current local project)
4. Remove any local WP build `rm -rf dist` (will delete any current local project)
5. `bin/dev quick_blank`

Despite the name, it's not so quick. Go grab a coffee.

**Comment by alexk1204** [comment]
@khawkins98 Hi Ken, thanks for your work. I looks good and works fine. I just want to know how we should handle the WP plugins that are missing (for migration, toolset types). Should I put them manually in the folder vfwp-external?

**Comment by khawkins98** [comment]
For the plugins specific to SiS we should put them in this repo, under `./wp-content/plugins/name_of_plugin`

For some of the purchased plugins we should check the license files to be sure there's no restriction against this (there usually isn't).

**Comment by khawkins98** [comment]
Merging this one in, suggest we do the SiS plugins in a new PR.

**Pull request merged**
