### PR TITLE
[WIP ]Feature/templates

### PR DESCRIPTION
**Pull request by alexk1204**

### CODE REVIEW

**Comment by khawkins98** [comment]
Hey Alex. Sorry, just saw this. Hopefully you've not been waiting on me — please do go ahead and merge when ready.

**Comment by khawkins98** [comment]
Ah, have just seen the "WIP"

Also, in case you weren't aware, github added a "draft PR" feature a little while ago: https://github.blog/2019-02-14-introducing-draft-pull-requests/

**Comment by alexk1204** [comment]
@khawkins98  Thanks, I have converted it into a draft pull request.

**Comment by khawkins98** [comment]
What's the plan or timeline for merging this into `master`? 

Just so when I'm working on the CSS changes, I'm working against the latest version.

**Pull request closed without merging**
